### ISSUE TITLE
ニュースリリース翻訳

### ISSUE THREAD

**Issue by naruoga** [naruoga/DFD2015-ja#3]
今日の日付なのだけど間に合うか。
news-20150225-01.ja.xhtml

**Comment by komiyatatsh** [comment]
アートワークという用語が日本では伝わりにくいので「画像素材」とかになると難しいでしょうか。

**Comment by komiyatatsh** [comment]
L24
「DFDに参加しているみんなと」
みんなと→みなさん、方々といったもうちょっとかためのような言葉とか…

**Comment by komiyatatsh** [comment]
L26
「去年何をやったか」
やった→行ったか　のほうが良いような気がします。

**Comment by naruoga** [comment]
「アートワーク」はちょっと悩みましたが、検索すると出てきますし一部辞書的なサイトもヒットするので、とりあえずそのままにしました。

L24とL26は指摘反映してpushしました。確認いただいて問題ないようならMLに投げたいと思います。

**Comment by komiyatatsh** [comment]
アートワークの件了解です。
L24,L26はこれでよいと思います。ありがとうございます。

**Comment by naruoga** [comment]
MLに投げました。レビューありがとうございます！

**Comment by naruoga** [comment]
反映されたのでチケット閉じます。
