### ISSUE TITLE
getinvolved査読

### ISSUE THREAD

**Issue by komiyatatsh** [naruoga/DFD2015-ja#5]
getinvolved.ja.xhtml

**Comment by komiyatatsh** [comment]
L17
「育てるためにできるか」→「育てるために何ができるか」
だとまずいでしょうか。

**Comment by komiyatatsh** [comment]
L39
「話しましょう、対面で、あるいは」→「顔を合わせて話しましょう、あるいは」
だとやわらかすぎ？

**Comment by komiyatatsh** [comment]
L60まで見ました。
続きはすいませんがお時間いただきます。

**Comment by naruoga** [comment]
L17, L39 共に修正しました。

**Comment by naruoga** [comment]
じつのところ

> Read this page to get inspired on 

を

> このページを読んで、（中略）、刺激を受けてください。

は訳として如何なもんかなあと思っております。よいアイディアがあればぜひ。

**Comment by komiyatatsh** [comment]
L17
「このページを読んで、DFDを今まで以上に大きく育てるために何ができるか、刺激を受けてください。」
ですが
「このページを読むことで、DFDを今まで以上に大きく育てるために何ができるかのきっかけとしてください。」
までひねると、Read this page ～の強さが無くなるかなあ。

**Comment by komiyatatsh** [comment]
L65
「招待状になるでしょう」→「誘いとなるでしょう」
はいかがですか。

**Comment by komiyatatsh** [comment]
L73
「あなたの政府とか、」→「あなたの政府や、」
－－
それと後半の「行政機関の場合」は日本ではどうなんだろうってうなってます。かっこ書きで訳注入れたりするとかもありなんでしょうか。

**Comment by naruoga** [comment]
L17, L65、それと L73の「あなたの政府や」については対応しました。チェックお願いします。

**Comment by naruoga** [comment]
「行政機関」のやつですが、

> If it is about a public administration, you might be more lucky if you ask for permission to set up a booth in front of the building.

の訳としての

> 行政機関の場合は、より幸運なことに、建物の前にブースを設置してもよいか聞くことができるでしょう。

は間違いな気がしてきました。
図書館とかの場合は運が良ければ中にブースを置かせてもらえるけど、行政機関（というか、この場合は県庁とか市役所という庁舎のことでしょうね）なら、前にブースを置かせて貰えるなら（図書館とかに比べて）さらにラッキーだね、ってことかと思いました。

荒い訳なのでコミットはしてないですが、

> 庁舎などの場合は、建物の前にブースを出す許可を貰えるだけも、より運がよいかもしれません。

とかがいいんでしょうかねえ。

**Comment by komiyatatsh** [comment]
（それが）もし行政機関（など）で、建物の前にブースを置けるならば、より幸運なことかもしれません。
－－とかですね。前半のask for permissionと後半のそれは同じことを指していると。

**Comment by naruoga** [comment]
なるほど。それもらいます。

**Comment by komiyatatsh** [comment]
L76
賞を授与するのくだり、ちょっと手入れすぎたかも。
－－－
L83～86（改行つぶしてます）
もしオープンな標準の分野で、良い事例であるような組織や自治体、企業があれば、その努力を評価し、彼らの活動を力づけるために賞を授与しましょう。<a href="/news/news.html">過去には</a>いろんなグループに証明書とケーキを授与しています。詳しくは<a href="prize-funding.html">「ドキュメント自由の日」の賞を与えるには</a>を。<br style="clear:both" />

**Comment by komiyatatsh** [comment]
あと今更ですが、
2か所ほど「いろんな」があるんですが（L83-86にもある）、それを「色々な」か「様々な」に置き換えられますか。
根拠としては「～とか」といった言い回しの修正と同義です。

**Comment by naruoga** [comment]
L83-86ですが概ねよいと思います。

「いろんな」は、もともとGetInvolvedはもっと柔らかく訳すつもりだった（一緒にやろうよ！的な感じで）のでその名残ですね。結局、全体的に硬い感じの訳になってしまったので、適当に変えておきます。

**Comment by naruoga** [comment]
あとここのcertificateは証明書なのかなあ。「賞状」ぐらいなのかなという気がします。

**Comment by komiyatatsh** [comment]
あ、賞状に+1です。
迷ってました。

**Comment by naruoga** [comment]
thx! とりあえずコミットしました。

**Comment by komiyatatsh** [comment]
L97〜
息継ぎがほしいかなと。
「有名人を招待して、」
「ハッカースペースや大学が、」

**Comment by komiyatatsh** [comment]
L104
DFDのメーリングリストを
→私たちはDFDのメーリングリストを

**Comment by komiyatatsh** [comment]
L107〜
ここはDFD、→ここはDFDや、
基本的なメディアです。→主要なメディアです。
L112
翻訳を貢献し→翻訳を役立て
はどうかな？

これで一周しました。

**Comment by naruoga** [comment]
概ね意見いただいたとおり反映しました。
一箇所だけ、L112の「あなた自身の翻訳を貢献し」はやや意訳ですが、

> あなた自身で翻訳を提案し
> にしました。これでMLに投げます。

**Comment by naruoga** [comment]
公開されているのでclose
