### ISSUE TITLE
about翻訳

### ISSUE THREAD

**Issue by naruoga** [naruoga/DFD2015-ja#6]
http://documentfreedom.org/about.ja.html

かなり超訳が多いです。

**Comment by komiyatatsh** [comment]
冒頭で3月のが抜けてるところを（すみませんみようみまねで）更新してみました。

**Comment by komiyatatsh** [comment]
遅くなってすみません。日本語訳を読んでて引っかかった部分2点変えてみました。

**Comment by naruoga** [comment]
あれ、pull-reqとかもらってます？見当たらないです……

**Comment by komiyatatsh** [comment]
うひぃ、ちょっと見直しますです

**Comment by naruoga** [comment]
公開されました。閉じ忘れ
